### ISSUE TITLE
JIRA field with name `Priority` does not exist 

### ISSUE THREAD

**Issue by openstacks** [DeloitteDigitalUK/jira-agile-metrics#11]
Test steps:
1: prepared config.yml

2:run it in docker
(py3venv) root@cloudcome:~/jira-agile-metrics# docker run -it  --rm -v $PWD:/data jira config.yml
 
Test result

Traceback (most recent call last):
  File "/usr/local/bin/jira-agile-metrics", line 11, in <module>
    load_entry_point('jira-agile-metrics==0.21', 'console_scripts', 'jira-agile-metrics')()
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/cli.py", line 49, in main
    run_command_line(parser, args)
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/cli.py", line 101, in run_command_line
    run_calculators(CALCULATORS, query_manager, options['settings'])
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/calculator.py", line 49, in run_calculators
    results[c.__class__] = c.run()
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/calculators/defects.py", line 45, in run
    priority_field_id = self.query_manager.field_name_to_id(priority_field) if priority_field else None
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/querymanager.py", line 77, in field_name_to_id
    raise ConfigError("JIRA field with name `%s` does not exist (did you try to use the field id instead?)" % name) from None
jira_agile_metrics.config.ConfigError: JIRA field with name `Priority` does not exist (did you try to use the field id instead?)

config.yml

> Connection:
```
>     Domain: http://192.168.103.23:8080 # your JIRA instance
>     username: Keven
>     password: qaz!wsx@edc3
```
> 
> Query: Project=CAAS AND assignee = currentUser() and due < endOfWeek()
> 
> Workflow:
>     Backlog: Backlog
>     Committed: Committed
>     Elaboration: Elaboration
>     Build: Build
>     QA:
>         - Code review
>         - Test
>     Done: Done
> 
> Output:
> 
>     Cycle time data:
>         - cycletime.csv
>         - cycletime.json
>     CFD data: cfd.csv
>     Scatterplot data: scatterplot.csv
>     Histogram data: histogram.csv
>     Throughput data: throughput.csv
>     Percentiles data: percentiles.csv
> 
>     Scatterplot chart: scatterplot.png
>     Scatterplot chart title: Cycle time scatter plot
> 
>     Histogram chart: histogram.png
>     Histogram chart title: Cycle time histogram
> 
>     CFD chart: cfd.png
>     CFD chart title: Cumulative Flow Diagram
> 
>     Throughput chart: throughput.png
>     Throughput chart title: Throughput trend
> 
>     Burnup chart: burnup.png
>     Burnup chart title: Burn-up
> 
>     Burnup forecast chart: burnup-forecast.png
>     Burnup forecast chart title: Burn-up forecast
>     Burnup forecast chart trials: 100 # number of Monte Carlo trials to run to estimate completion date
> 
>     WIP chart: wip.png
>     WIP chart title: Work in Progress
> 
>     Ageing WIP chart: ageing-wip.png
>     Ageing WIP chart title: Ageing WIP
> 
>     Net flow chart: net-flow.png
>     Net flow chart title: Net flow
> 
> 
> 
> 
>     Defects query: issueType = Bug
>     Defects window: 6
>     Defects priority field: priority
>     Defects priority values:
>       - Low
>       - Medium
>       - High
>         #Defects type field: Root cause
>     Defects type values:
>       - Config
>       - Data
>       - Code
>         #Defects environment field: Environment
>     Defects environment values:
>       - SIT
>       - UAT
>       - PROD
>     Defects by priority chart: defects-by-priority.png
>     Defects by priority chart title: Defects by priority
>     Defects by type chart: defects-by-type.png
>     Defects by type chart title: Defects by type
>     Defects by environment chart: defects-by-environment.png
>     Defects by environment chart title: Defects by environment
> 
>

**Comment by optilude** [comment]
Your configuration is referring to a field with the title Priority, and no such field exists. Like it says in the error, no?

**Comment by optilude** [comment]
Also - you pasted your password into this issue. I suggest you change it.

**Comment by openstacks** [comment]
It is a fault password.

**Comment by openstacks** [comment]
I want to create defect chart ,but when i run it say no Priority field.

raise ConfigError("JIRA field with name %s does not exist (did you try to use the field id instead?)" % name) from None
jira_agile_metrics.config.ConfigError: JIRA field with name Priority does not exist (did you try to use the field id instead?)

**Comment by optilude** [comment]
Right. The config is referring to that field but your JIRA instance dose that have it. You need to change the config to match your JIRA setup.

I suspect the erroneous line is:

    Defects priority field: priority

**Comment by openstacks** [comment]
Thanks!
I changed 
  Defects priority field: priority
  to 
Defects priority field: Priority

It still throws this error:
```
(py3venv) root@cloudcome:~/jira-agile-metrics# docker run -it -p 8080:80 --rm -v $PWD:/data jira config.yml
Traceback (most recent call last):
  File "/usr/local/bin/jira-agile-metrics", line 11, in <module>
    load_entry_point('jira-agile-metrics==0.21', 'console_scripts', 'jira-agile-metrics')()
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/cli.py", line 49, in main
    run_command_line(parser, args)
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/cli.py", line 101, in run_command_line
    run_calculators(CALCULATORS, query_manager, options['settings'])
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/calculator.py", line 49, in run_calculators
    results[c.__class__] = c.run()
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/calculators/defects.py", line 45, in run
    priority_field_id = self.query_manager.field_name_to_id(priority_field) if priority_field else None
  File "/usr/local/lib/python3.7/site-packages/jira_agile_metrics/querymanager.py", line 77, in field_name_to_id
    raise ConfigError("JIRA field with name `%s` does not exist (did you try to use the field id instead?)" % name) from None
jira_agile_metrics.config.ConfigError: JIRA field with name `Priority` does not exist (did you try to use the field id instead?)
```
