### ISSUE TITLE
Question: Convert to hours or timestamp

### ISSUE THREAD

**Issue by cstergianos** [DeloitteDigitalUK/jira-agile-metrics#19]
Hello,

I am just familiarizing with the tool and till now I am unable to get some specific metrics I need. For instance I am not sure how to setup my config.yaml file in order to get the exact days since a story move from Todo to In Progress. Is this even possible?

If yes I am looking for something accurate, maybe even a timestamp.

**Comment by optilude** [comment]
If you use the `cycletime.csv` style file output you will get exact timestamps of transition from each state. Please read the README carefully and I suggest you use the basic examples to set up an extract to play with.

**Comment by BasitAli** [comment]
Sorry, but using cycletime.csv and still only see the date and not the timestamp.
