### ISSUE TITLE
Docker build fails due to statsmodel installation issue

### ISSUE THREAD

**Issue by MrReasonable** [DeloitteDigitalUK/jira-agile-metrics#3]
Due to https://github.com/statsmodels/statsmodels/issues/4635, the Docker image fails to build.  One solution is to install numpy as a separate step prior to installing the contents of requirements.txt

**Comment by optilude** [comment]
This is definitely not happening for me locally (on a Mac) or on Docker Hub. Given the issue you reference is closed, I'm going to close this, but if you still have problems, please re-open.
