### ISSUE TITLE
Support for custom field for the Issue Count for example Story Points

### ISSUE THREAD

**Issue by digiguru** [DeloitteDigitalUK/jira-agile-metrics#47]
I was wondering if it's currently possible to utualise Story Points (or another custom field) to calculate the Mote-carlo simulation and other reports in the system.

To do this I would suggest a new global parameter eg...

```
Custom Sum Field: Story Point
Default Sum Value: 5 #in scenarios where the storypoint is absent we can default it to a value, and if not then these issues are ignored.
```
Does this make sense?

**Comment by optilude** [comment]
It's not supported. But I'm also not sure it's a very good idea. I don't think you could reliably use that for forecasting in this way at all. In fact, this tool (and the Actionable Agile tool that we can export to) is used to create more accurate and lower-effort forecasts *without* story points (or days or equivalent assumption/guess-based bottom-up estimation).
