### ISSUE TITLE
Missing Completion dates on Issues that moved backwards

### ISSUE THREAD

**Issue by pacovi** [DeloitteDigitalUK/jira-agile-metrics#6]
When retrieving the data for issues that have been transitioned back, I get the following message in the logger:

`Issue %s moved backwards to %s , wiping data for subsequent step %s`, from the file `calculators/cycletime.py`.

This causes that issues that are currently in the final state, do not have any transition time, also, transitions between other areas are blank. The CSV data is not usable, as issues that are in the final state do not have the required information to calculate cycle times, throughput, etc...

Getting rid of that for loop seems to provide some data, but it is unclear how reliable is the data afterwards.

**There's an issue when an issue was moved backwards and then was moved again to a final state.**

The issue is present in `jira-agile-metrics`, but has also been verified in `jira-metrics-extract`.

**Comment by optilude** [comment]
I'm not really following. Can you give a more concrete example?

Please note that the logic of what we do when things move backwards is relatively carefully designed. Not saying it couldn't have bugs, but the behaviour of wiping subsequent dates is deliberate. (In general, moving things backwards in a Kanban system is problematic)

**Comment by pacovi** [comment]
Hi @optilude,

Thanks for the response, sorry if I was not clear enough.

The scenario is a JIRA Cloud instance with a **Kanban Simplified Workflow**.

Consider the following workflow with 5 states: (Q)ueue, (R)eady, A, B, (D)one; being (D)one the final state, (Q)ueue the initial state (a.k.a. Backlog), the rest are states "In Progress".

Cycle time is the time elapsed between the moment on which the issue was started (moved from (Q)ueue to an In progress state) and the moment on which the issue was moved to a final state, e.g. (D)one.

My understanding is the following:
- When an issue does Q -> R -> D; Start time is (Q->R), end-time is (R->D).
- If an issue does Q -> R -> A -> D; that is, more than one "In Progress" state in between; start time should be (Q->R), end-time (A->D).  In these cases issue is detected to "have moved backwards".
- If an issue does Q -> R -> ... -> D -> A -> D; that is, a move back, I would expect that the "moved back" is detected. Start time is (Q->R) and end-time is the last occurrence of (A->D).

What I have seen is that **whenever the "move back" is detected**, it does not matter that the issue is currently in the final state, **there's no end-time detected at all**. Hence, there's no data for the cycle-time calculation. Note that is not restricted to the fact of "moving back", but the "move back" being detected. 

Even if the issue is in a final-state. The "move back" seems to also be detected whenever there's a transition between two "In Progress" states is done, e.g. A->B from the example above.

Getting rid of that handling from `calculators/cycletime.py` yields end-times in those cases, but I am not sure about the implications, it could yield wrong results in cycle-time calculations.

Please do let me know if I did not explain it clearly.

Thanks a lot for your time,
Francisco

**Comment by optilude** [comment]
Hi,

In this example, what is your Workflow config?

I agree this doesn’t sound right:

> If an issue does Q -> R -> A -> D; that is, more than one "In Progress" state in between; start time should be (Q->R), end-time (A->D). In these cases issue is detected to "have moved backwards".

This still confuses me:

> What I have seen is that whenever the "move back" is detected, it does not matter that the issue is currently in the final state, there's no end-time detected at all. Hence, there's no data for the cycle-time calculation. Note that is not restricted to the fact of "moving back", but the "move back" being detected.

Isn’t the final state by definition the final state? How can you “move back” to the final state?

The algorithm for “move backwards” is basically:

- walking through all workflow changes in the history in order
- map target state for each transition to a step in the Workflow config
- set this as the current workflow step
- if the new step is an “earlier” step than the precious step, wipe dates for any steps subsequent to the current step

This is the relevant code, by the way:

```
                    found_cycle_name = False
                    for cycle_name in cycle_names:
                        if not found_cycle_name and cycle_name == snapshot_cycle_step_name:
                            found_cycle_name = True
                            continue
                        elif found_cycle_name and item[cycle_name] is not None:
                            logger.info("Issue %s moved backwards to %s, wiping data for subsequent step %s", issue.key, snapshot_cycle_step_name, cycle_name)
                            item[cycle_name] = None
```

Here `snapshot_cycle_step_name` is the name of the step from the Workflow configuration in the config file that maps to the target of the JIRA transition. It's hard for me to see how this could exhibit the behaviour I think you are describing, but I may be missing something.

The best way for us to figure this out would be to write a test that exhibits the problem. If you fancy having a go, look at `cycletime_test.py`. This sets up a fixture with some fake JIRA issues that have a history of workflow transitions (the map of workflow to JIRA transitions is set up in `conftest.py`), and then runs the calculator and confirms the output looks right.

**Comment by pacovi** [comment]
Hi,

I fully agree with the proposed approach. I'll take a look at `cycletime_test.py`. My feeling is that the behavior observed could come from how the workflow is interpreted. Here's the workflow of the example:

![gfcu_example_workflow](https://user-images.githubusercontent.com/6522045/49794196-4d7f0a00-fd37-11e8-99ea-f58fc70fc771.png)

I am not sure how the "steps" for the transitions are mapped in this case, as the step itself is a "free" step, that is, all transitions are possible.

With respect to:

> This still confuses me:
>> What I have seen is that whenever the "move back" is detected, it does not matter that the issue is currently in the final state, there's no end-time detected at all. Hence, there's no data for the cycle-time calculation. Note that is not restricted to the fact of "moving back", but the "move back" being detected.

My feeling is that the "move back" is wrongly detected on a transition between intermediate steps, and then, all the following transitions are cancelled.

**So far I managed to extract a "failure case" from my real data and look into it,** will try to reproduce it as a test but not sure yet how to configure the test. **Here's the current data as of now:**

* From `cycletime.py`, printing `self.settings['cycle']` yields:
```
[
{'type': 'backlog', 'statuses': ['Queue'], 'name': 'Backlog'},
{'type': 'accepted', 'statuses': ['Ready'], 'name': 'Ready'},
{'type': 'accepted', 'statuses': ['Status_A', 'Status_B'], 'name': 'In Progress'},
{'type': 'complete', 'statuses': ['Done'], 'name': 'Done'}
]
```

* The JIRA web view shows the following Activity in the History tab:
  * UserA created issue - 30/Nov/18 5:42 PM
  * UserA made changes - 30/Nov/18 5:42 PM
    * Field	Original Value	New Value
    * Status	Queue [ 10006 ]	Ready [ 10007 ]
  * UserA made changes - 30/Nov/18 5:46 PM
    * Status	Ready [ 10007 ] Status_A [ 10173 ]
  * UserB made changes - Yesterday
    * Resolution		Done [ 10000 ]
    * Status	Status_A [ 10173 ]	Done [ 10053 ]
* This corresponds to the transition Q -> R -> A -> D

I observe the following behavior:
- Detecting the cycles, leaving the code 'as is'
  - Printed output shows deleted transitions due to "moved backwards" handling loop. `scatterplot.csv` has only the headers, no dates on any transition happened.
- Commenting out the loop you mentioned that detect cycles in `cycletime.py`:
  - `scatterplot.csv` shows timestamps for the transitions mentioned above.

Note that there's no real "moved backwards" happening, but it's detected as such.

**Comment by optilude** [comment]
One other thing, if you're feeling brave... put a breakpoint (`import pdb; pdb.set_trace()`) in `cycletime.py` at line 89 (https://github.com/DeloitteDigitalUK/jira-agile-metrics/blob/master/jira_agile_metrics/calculators/cycletime.py#L89). You can then step through (with `n`) and print (with `pp <variable>`) what's going on.

If you do this, I suggest making the query as specific as possible so you don't step through a deluge of issues. But it should be possible here to see what's going on.

**Comment by pacovi** [comment]
Thanks for the info! Will try to dig further into it.

FYI the `Workflow:` section:
```
Workflow: 
    Backlog: Queue
    Selected: Ready
    In Progress:
         - A
         - B
    Done: Done
```

**Comment by pacovi** [comment]
Hi @optilude,

a bit of debugging uncovered the hiccup, I have raised a pull-request  #7  for the fix.

Cheers,
Francisco

**Comment by optilude** [comment]
Thank you!

I've just pushed a version of your PR that just applies the fix in a slightly different place.

Can you test it before I release it?

**Comment by pacovi** [comment]
Tested! works as well, thanks!
