### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'lower' + Contribution guide?

### ISSUE THREAD

**Issue by andretzermias** [DeloitteDigitalUK/jira-agile-metrics#60]
Hey there, 
I'm looking forward to testing this tool! 

I got 2 questions:
1. I'm blocked at the very first steps though  - seems like the `cycleTimeCalculator` isn't able to parse a field. Maybe its returning `None`?
 
```
DEBUG: Starting new HTTPS connection (1): $url
DEBUG: https://roofrapp.atlassian.net:443 "GET /rest/api/2/serverInfo HTTP/1.1" 200 None
DEBUG: Resolving JIRA fields
DEBUG: $url "GET /rest/api/2/field HTTP/1.1" 200 None
INFO: CycleTimeCalculator running...
ERROR: 'NoneType' object has no attribute 'lower'
```

2. I'm trying to also install the software locally to add some debugging options around where this is failing, but with my limited python experience, I cannot execute `cli.py` sucesfully (there's an `import` error. If there's a contributor's guide, I'd love to see it)

**Comment by GrimmiMeloni** [comment]
Hey, I don't know about the first point on your list, but I got the second one going here.
I did the following:

Created a `jira_agile_metrics/__main__.py` (relative to project root) with the following contents.  

```python3

import re
import sys
from jira_agile_metrics.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

You can now call it out of the virtualenv as follows:

```shell
/usr/bin/env <projectRoot>/.env/bin/python -m jira_agile_metrics
```
You can provide commandline switches as needed.


Also, you can run this in vsCode's debugger with a `launch.json` like the following (just replace `<somePath>` and `<projectRoot>`):

```
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "cli.py with config",
            "python": "<projectRoot>/.env/bin/python",
            "type": "debugpy",
            "request": "launch",
            "console": "integratedTerminal",
            "args": "<somePath>/config.yaml",
            "env": {"PYTHONPATH": "<projectRoot>"},
            "module": "jira_agile_metrics",
            "cwd": "${workspaceFolder}"
        }
    ]
}
```


Finally, if your environment does not support username/password auth, you can provide a personal token (created via your JIRA profile) by hacking/patching this line:

https://github.com/DeloitteDigitalUK/jira-agile-metrics/blob/1fb00bfa9e80db21e1aba2a4ec61eb9fe9d4c111/jira_agile_metrics/cli.py#L219

replacing 

`basic_auth=(username, password),` with `token_auth=("<yourToken>"),`

Happy hacking!

**Comment by andretzermias** [comment]
I ended up fixing the issue - it was a problem with my config.yml file's indentation - but I had to get deep into it with logging calls.

To run the web interface locally, I followed the setup guide in `Dockerfile.develop`:

```
docker build -t jira-agile-metrics-dev -f Dockerfile.develop .
docker run -it --rm -p 5000:5000 -v $PWD:/app --env FLASK_DEBUG=1 jira-agile-metrics-dev jira-agile-metrics --server 0.0.0.0:5000
```
